#!/bin/bash

date=$(bash -c "LC_ALL=en_GB.utf8 date '+%B %d, %Y'")

cd scripts
mime run upd-epub-to-jp.tl --infile ../4300-h/4300-h.htm --outfile updated-to-jp.htm </dev/null
mime run add-anno.tl --date "${date}" --anno_path /datadir/annotations-raw --infile updated-to-jp.htm --outfile annotated.htm --colour_outfile colour_annotated.htm </dev/null

ebookmaker \
	--make epub.images \
	--title Ulysses \
	--author "James Joyce" \
	--output-file /datadir/ulysses-annotated.epub \
	--cover ../cover-monochrome.jpg \
	annotated.htm

ebookmaker \
	--make epub.images \
	--title Ulysses \
	--author "James Joyce" \
	--output-file /datadir/ulysses-annotated-colour.epub \
	--cover ../cover.jpg \
	colour_annotated.htm

# ebookmaker's epub.images make-type writes "<output-file>-images-epub.epub";
# rename to the expected filenames (as the Makefile's epub target does).
mv /datadir/ulysses-annotated.epub-images-epub.epub /datadir/ulysses-annotated.epub
mv /datadir/ulysses-annotated-colour.epub-images-epub.epub /datadir/ulysses-annotated-colour.epub
